[package]
name = "ant_colony"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vn_engine = { path= "../vn_engine" }
rand_pcg = "0.3.1"
rand_seeder = "0.2.3"
rand = "0.8.5"
